# Generated by Django 2.1.7 on 2019-08-05 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('_tasks', models.TextField(verbose_name='Tasks')),
                ('pattern', models.CharField(default='{}', max_length=64, verbose_name='Pattern')),
                ('_options', models.CharField(default='', max_length=1024, verbose_name='Options')),
                ('_hosts', models.TextField(blank=True, verbose_name='Hosts')),
                ('run_as_admin', models.BooleanField(default=False, verbose_name='Run as admin')),
                ('run_as', models.CharField(default='', max_length=64, null=True, verbose_name='Username')),
                ('_become', models.CharField(default='', max_length=1024, verbose_name='Become')),
                ('created_by', models.CharField(default='', max_length=64, null=True, verbose_name='Create by')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ops_adhoc',
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='AdHocRunHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Adhoc raw result')),
                ('_summary', models.TextField(blank=True, null=True, verbose_name='Adhoc result summary')),
            ],
            options={
                'db_table': 'ops_adhoc_history',
                'get_latest_by': 'date_start',
            },
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('finished', 'finished')], db_index=True, max_length=128)),
                ('log_path', models.CharField(blank=True, max_length=256, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('command', models.TextField(verbose_name='Command')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('is_finished', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('hosts', models.ManyToManyField(to='assets.Asset')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('interval', models.IntegerField(blank=True, help_text='Units: seconds', null=True, verbose_name='Interval')),
                ('crontab', models.CharField(blank=True, help_text='5 * * * *', max_length=128, null=True, verbose_name='Crontab')),
                ('is_periodic', models.BooleanField(default=False)),
                ('callback', models.CharField(blank=True, max_length=128, null=True, verbose_name='Callback')),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'ops_task',
                'get_latest_by': 'date_created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'created_by')},
        ),
    ]
